apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: w2l38mp4o-python 
  janus-idp.io/tekton: w2l38mp4o-python
  backstage.io/kubernetes-id: w2l38mp4o-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w2l38mp4o-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml