apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w2l38mp4o-python-gitops
  description: This is GitOps manifest for w2l38mp4o-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=w2l38mp4o-python
    backstage.io/kubernetes-id: w2l38mp4o-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w2l38mp4o-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w2l38mp4o-python
