apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w2l38mp4o-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w2l38mp4o-python 
  name: w2l38mp4o-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: w2l38mp4o-python 
